// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace MVCDemo.Models;

public partial class CourseList
{
    public int CourseId { get; set; }
    public string Title { get; set; }

    [UIHint(nameof(Credits))]
    public int Credits { get; set; }

    public string Description { get; set; }

    public string Slug { get; set; }

    public DateTime StartDate { get; set; }
}